Mobile single level sidenav
GovTechSG/developer.gov.sg pull request #1089
Opened 2021-12-13 10:30 UTC by kuramochi-coder

Added mobile view for singe level sidenav

2021-12-15 06:40 UTC, teochengyong requested changes
Another question, currently we have 2 layouts. 
- Layout-page and Layout-sidenav. Would it be confusing for layout-page to have the sidenav as well?

2021-12-15 07:26 UTC, kuramochi-coder commented on _layouts/layout-page.html
> +{% endif %}
Currently layout-default also contains a mobile multi-level sidenav which appears at the very top. In order to position the single-level mobile sidenav in the middle after the page headers, it had to be placed in layout-page. 

Will change the current mobile single-level sidenav to a partial file.

2021-12-27 08:12 UTC, teochengyong reviewed
Mostly looks good and just minor comment

2021-12-27 10:28 UTC, teochengyong approved these changes
LGTM  🙂

2021-12-27 10:46 UTC, merged