Sgts page change hosting service part
GovTechSG/developer.gov.sg pull request #1217
Opened 2022-04-25 08:53 UTC by anbarisker

2022-04-27 05:32 UTC, teochengyong requested changes
Looks okay otherwise @anbarisker !

2022-04-27 05:32 UTC, teochengyong commented on collections/_singapore-government-tech-stack/overview/index.html
> +          <div class="col is-2-desktop is-paddingless host-box is-felx " >
```suggestion
          <div class="col is-2-desktop is-paddingless host-box is-flex " >
```

2022-04-27 05:32 UTC, teochengyong commented on collections/_singapore-government-tech-stack/overview/index.html
> +          <div class="col is-4-desktop is-paddingless is-felx">
do you need this?

2022-04-27 06:09 UTC, anbarisker commented on collections/_singapore-government-tech-stack/overview/index.html
> +          <div class="col is-4-desktop is-paddingless is-felx">
removed the col div

2022-04-29 06:41 UTC, teochengyong approved these changes
LGTM!

2022-04-29 06:42 UTC, merged