Update vica writeup billy
GovTechSG/developer.gov.sg pull request #1655
Opened 2023-04-06 02:21 UTC by billyteo

2023-04-18 08:55 UTC, candyyap-gvt requested changes
Hi Billy, please see below for my comments

1. Para 1: "...to develop chatbots that are more...", to remove the word "more"...just say chatbots that are efficient....and useful for end users.... - this is to keep it succinct
2. Para 2: NLP, need to include natural language processing. Can we also remove "compared to the older AskJamie (I think it should be one word if not wrong_"? Just be more direct and say how good the product is.
3. Don't think we need to explain what is NLP (most people usually know what is it le) but if need, can we streamline it to 1 sentence? + do we usually say is a branch or component?
4. Can we link the examples to the actuall site for those available?
5. The last 3 sentences in benefits seems a bit extra. Can this be park under roadmap or what's next header?
6. For benefits, should list out the actual benefits first then the current way
7. Why is there such a big spacing between the benefits for agencies and citizens?
8. Can we link DSAID in success stories to the DSAI collection?

2023-04-26 03:44 UTC, candyyap-gvt requested changes
I thought we are no longer using Success Stories?

2023-04-26 05:04 UTC, billyteo commented
> I thought we are no longer using Success Stories?

Oh ok, have changed to Customer Stories. 

This is what we agreed on yah?

2023-04-26 05:38 UTC, candyyap-gvt approved these changes

2023-04-26 05:38 UTC, merged