updated cloud-file-transfer.md
GovTechSG/developer.gov.sg pull request #742
Opened 2021-08-04 05:34 UTC by meenakartik

1. Added a one-liner title
2. Slight changes to the intro
3. Added a section Why Choose CFT
4. Added a benefit
5. Revised Features section
6. Added image to illustrate how it works. (How_it_works.png)

2021-08-04 07:38 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +Consistent and accessible data in real-time across multiple touchpoints.
may need to rephrase this a bit more. Data integrity should also include things like tamper-proof

2021-08-04 07:39 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +###Powering secure, efficient, robust file transfers
Formatting issue: you need a space after ###

2021-08-04 07:40 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
>  ### A Singapore Government Tech Stack (SGTS) Product
Let's remove the whole section. CFT is part of service layer. Maybe a liner in the introduction that says CFT is an  SGTS product

2021-08-04 07:41 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +### Why choose CFT?
Combine this section with benefits

2021-08-04 07:42 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +### CFT Workflow
Let's rename this to How CFT works

2021-08-04 07:46 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +##### Streamlined file transfer workflows
Should mention that CFT workflows are highly configurable

2021-08-04 07:47 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +##### Lightweight API-driven service
API Driven already mentioned a few times, maybe can omit it here.. since its already covered under benefits > Plug & Play

2021-08-04 07:50 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +Enhance the level of security with user-defined file transfer policies and customizable workflows.
does really explain how we made file transfers secure. can mention encryption at rest and in transit, pgp encryption and decryption

2021-08-04 07:52 UTC, zenchua requested changes
Some formatting issues. Can we also add in our sandbox and production sign up forms?

2021-08-04 08:01 UTC, zenchua commented on collections/_singapore-government-tech-stack/communications/cloud-file-transfer.md
> +###Powering secure, efficient, robust file transfers
Can we use "Overview" instead?

2022-05-26 07:02 UTC, seng-siong commented
closing this PR due to inactivities.

2022-05-26 07:02 UTC, closed without merging