Comms Engagement Playbook
GovTechSG/developer.gov.sg pull request #961
Opened 2021-09-27 11:12 UTC by candyyap-gvt

2021-12-21 02:53 UTC, kuramochi-coder reviewed
![image](https://user-images.githubusercontent.com/47944476/146862453-ed6e53f6-4dd2-4cc9-9ce2-66ccf0fe1c87.png)
might want to edit the description portion

![image](https://user-images.githubusercontent.com/47944476/146862571-c2a4ed67-8edf-40df-8185-6f7e6a2735aa.png)
within the resources folder, the overview.html should be renamed to index.html as shown, else the original sidenav selection will not work

Have tested the links to resources, all working fine

2021-12-21 03:15 UTC, teochengyong requested changes
Overall looks good, please help to remove unused codes and comments.
- There is a description missing in the communities page
http://localhost:4000/communities/index.html
![image](https://user-images.githubusercontent.com/2618932/146865016-ba467351-1b67-4edf-a1a3-8322f3e7361c.png)

- Added a PR here https://github.com/GovTechSG/developer.gov.sg/pull/1093 to remove the use of inline css.

2021-12-21 14:49 UTC, candyyap-gvt commented on _data/communities.yml
> +    insert a description
done

2021-12-21 14:50 UTC, candyyap-gvt commented on _includes/community-resources-listing.html
> +</div>
removed

2021-12-21 14:56 UTC, candyyap-gvt commented on collections/_communities/building-a-community/resources/interview-with-mindy-lim.md
> +<p></p>
i assume u meant the <p></p>? nope not needed. Thanks

2021-12-21 15:00 UTC, candyyap-gvt commented on collections/_communities/building-a-community/resources/interview-with-mindy-lim.md
> +<p></p>-->
removed

2021-12-21 15:01 UTC, candyyap-gvt commented on collections/_communities/building-a-community/resources/interview-with-min-li.md
> +<p></p>
ok

2021-12-21 15:01 UTC, candyyap-gvt commented on collections/_communities/building-a-community/resources/interview-with-min-li.md
> +<p></p>-->
removed

2021-12-21 15:03 UTC, candyyap-gvt commented on collections/_communities/building-a-community/resources/overview.html
> +<!--{% include community-resources-listing.html %}-->
done

2021-12-24 02:43 UTC, kuramochi-coder approved these changes
Looks good, sgds css classes are used as far a possible and content loads correctly

2021-12-24 03:06 UTC, merged